# Generated by Django 6.0.2 on 2026-03-10 16:04

import app.models
import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='especial',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('capa-dura', 'Capa Dura'), ('impressão-especial', 'Impressão Especial'), ('contra-capa', 'Contra Capa')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livros',
            name='video_demonstracao',
            field=models.FileField(blank=True, null=True, upload_to=app.models.caminho_livro, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='livros',
            name='capa',
            field=models.ImageField(upload_to=app.models.caminho_livro, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'webm', 'png'])]),
        ),
    ]
