# Generated by Django 6.0.2 on 2026-03-10 16:31

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_livros_especial_livros_slug_livros_vendido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='especial',
            new_name='caracteristicas',
        ),
        migrations.AddField(
            model_name='livros',
            name='categoria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('artes', 'Design + Arte + Tattoo'), ('nerd', 'Quadrinhos + Nerdices'), ('estudos', 'História + Sociologia + Filosofia + Linguística'), ('brumed', 'Bruxaria + Meditação'), ('erotica', 'Erótica')], default=None, max_length=25, null=True),
        ),
    ]
