# Generated by Django 6.0.2 on 2026-03-11 16:50

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_especial_livros_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='caracteristicas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('capa-dura', 'Capa Dura'), ('impressão-especial', 'Impressão Especial'), ('contra-capa', 'Contra Capa')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('artes', 'Design + Arte + Tattoo'), ('nerd', 'Quadrinhos + Nerdices'), ('estudos', 'História + Sociologia + Filosofia + Linguística'), ('brumed', 'Bruxaria + Meditação'), ('erotica', 'Erótica')], default=None, max_length=200, null=True),
        ),
    ]
