# Generated by Django 6.0.2 on 2026-03-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_livros_caracteristicas_alter_livros_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
