# Generated by Django 6.0.2 on 2026-03-21 02:35

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_livros_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='data_de_publicacao',
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(upload_to=app.models.caminho_livro, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'webp', 'png'])]),
        ),
    ]
