# Generated by Django 6.0.2 on 2026-03-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_livro_data_de_publicacao_alter_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(max_length=2000),
        ),
    ]
