# Generated by Django 6.0.2 on 2026-03-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_livro_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(max_length=8900),
        ),
    ]
