# Generated by Django 6.0.2 on 2026-03-30 14:27

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_livro_editora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('artes', 'Design + Arte + Tattoo'), ('nerd', 'Quadrinhos + Nerdices'), ('estudos', 'História + Sociologia + Filosofia + Linguística'), ('brumed', 'Bruxaria + Meditação'), ('erotica', 'Erótica')], default=['artes'], max_length=200),
        ),
    ]
