# Generated by Django 6.0.2 on 2026-04-06 15:05

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_livro_video_demonstracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(default='media/defaults/hmarch.webp', upload_to=app.models.caminho_livro, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'webp', 'png', 'jpeg'])]),
        ),
    ]
