# Generated by Django 6.0.2 on 2026-04-27 19:01

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(default='defaults/hmarch.webp', upload_to=app.models.caminho_livro, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'webp', 'png', 'jpeg'])]),
        ),
    ]
